"""
Django settings for holons project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
# turn sentry off for local env
# import sentry_sdk
# from sentry_sdk.integrations.django import DjangoIntegration

# sentry_sdk.init(
#     dsn="",
#     integrations=[DjangoIntegration()],
#     traces_sample_rate=1.0,
#     environment='development',
# 
#     # If you wish to associate users to errors (assuming you are using
#     # django.contrib.auth) you may enable sending PII data.
#     send_default_pii=True
# )


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False
ENV = 'develop'

ALLOWED_HOSTS = ['localhost', 'localhost:8080', 'localhost:8000', '127.0.0.1']

CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_jsonfield_backport',
    'djmoney',
    'imagefit',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',

    'modelcluster',
    'taggit',

    'ls.joyful',
    'ls.joyous',
    'wagtail.contrib.modeladmin',

    'corsheaders',
    'django_mailbox',
    # 'webpack_loader',
    'holons',
    'accounts',
    'invitation',
    'social',
    'email_api',
    'rays',
    'fora',
    'moneta',
    'relations',
    'health',
    'campaigns',
    'timer',
    'meetings',
    'purpose',
    'subscription',
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'holons.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

FRONTEND_DIR = os.path.join(BASE_DIR, '../frontend')

WSGI_APPLICATION = 'holons.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'db',
        'PORT': 5432,
        'TEST': {
            'NAME': 'holons_test_db',
            'ENGINE': 'django.db.backends.sqlite3'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/usg/'

STATIC_ROOT = os.path.join(str(BASE_DIR), "static/")
MEDIA_ROOT = os.path.join(str(BASE_DIR), "usg/")

STATICFILES_DIRS = [
    os.path.join(str(BASE_DIR), "../static/build"),
]

MODOBOA_MAIL_API_URL = ""
MODOBOA_MAIL_API_KEY = ""
SENDGRID_API_KEY = ""
SENDGRID_DOMAINS_API_KEY = ""
SENDGRID_DOMAINS_SUBUSER = ""
SENDGRID_DOMAINS_IP = ""

WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': DEBUG,
        'BUNDLE_DIR_NAME': '/bundles/',  # must end with slash
        'STATS_FILE': os.path.join(FRONTEND_DIR, 'webpack-stats.json'),
    }
}

MASTER_RAY_PK = 

# TELEGRAM_API_ID = 
# TELEGRAM_API_HASH = ''
TELEGRAM_API_ID = 
TELEGRAM_API_HASH = ''
MATRIX_MASTER_USER = ''
MATRIX_MASTER_PASSWORD = ''

# Reddit settings / 
REDDIT_URL = ''
REDDIT_OAUTH_URL = ''
REDDIT_CLIENT_ID = ''
REDDIT_CLIENT_SECRET = ''
REDDIT_PASSWORD = ''
REDDIT_USERNAME = ''

TWILIO_SID = ''
TWILIO_TOKEN = ''

CEO_PHONE = ''
CTO_PHONE = ''

SESSION_COOKIE_AGE = 180*24*60*60  # 180 days


TAIGA_API_URL = ''
TAIGA_HEADERS = {'Content-type': 'application/json', 'Authorization': 'Token ' + ''}
TELEPORT_API_URL = ''
LOGIN_API_HOSTNAME = ''

WAGTAIL_SITE_NAME = 'Holons'
JOYOUS_THEME_CSS = "/static/joyous/css/joyous_forest_theme.css"
USERPIC_UPLOAD_DIR = 'usg/soulspics'

X_FRAME_OPTIONS = 'ALLOWALL'
XS_SHARING_ALLOWED_METHODS = ['POST','GET','OPTIONS', 'PUT', 'DELETE']
DEFAULT_USERPIC = 'static/img/soul-pic3.jpg'

SHELL_PLUS_IMPORTS = [
  'from social.views import update_social_graph',
]

RAY_SOURCES = [
    'mercury',
    'odysseus',
    'athena',
    'talant',
    'moneta',
    'fora',
    'pheme',
    'grintender',
]

DEFAULT_RAY_MESSAGES = {
    'mercury': 'Hello from Mercury',
    'odysseus': 'Hello from Odysseus',
    'athena': 'Hello from Athena',
    'talant': 'Hello from Talant',
    'moneta': 'Hello from Moneta',
    'fora': 'Hello from Fora',
    'pheme': 'Hello from Pheme',
    'grintender': 'Hello from Grintender',
}

IMPERSONATE_MENU_AVAILABLE_TO = [
  'disabled_01',
  'disabled_02',
  'disabled_03',
  'disabled_04',
  'disabled_05',
  'disabled_08',
  '79219890902',
  '79213173065',
  '79136661890',
]

IMPERSONATE_PROFILES = [
    'disabled_01',
    'disabled_02',
    'disabled_03',
    'disabled_04',
    'disabled_05',
    'disabled_08',
    '79219890902',
    '79213173065',
    '79136661890',
]

RAYS_SOURCE = 'Talent HbAI'

HASHID_FIELD_SALT = "2V2wMPUk7VLAfQrAdanqNsB4kmUQxgRL"

ACCOUNT_STATUSES = [
  'core',
  'classic',
  'gold',
  'coin',
]

STRIPE_API_VERSION = '2020-08-27'
STRIPE_SECRET_KEY = ''
STRIPE_PUBLISHABLE_KEY = ''
STRIPE_WH_SIGNING_SECRET = ''
SUBSCRIPTION_PRICE = 
SUBSCRIPTION_PRODUCT_ID = ''
SUBSCRIPTION_PRICE_ID = ''
SUBSCRIPTION_INSTALL_FEE_PRODUCT_ID = ''
SUBSCRIPTION_INSTALL_FEE_PRICE_ID = ''
# STRIPE webhooks
WH_PAYMENT_INTENT_SUCCEEDED = 'payment-intent-succeeded/'
WH_PAYMENT_INTENT_CANCELED = 'payment-intent-canceled/'
WH_COMMON = 'wh-common/'
