"""
Django settings for holons project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from .country_codes import json as country_codes_json
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

sentry_sdk.init(
    dsn="",
    integrations=[DjangoIntegration()],
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '127.0.0.1:8080']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_jsonfield_backport',
    'rest_framework',
    'djmoney',
    'imagefit',

    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',
    'wagtail.api.v2',

    'modelcluster',
    'taggit',

    'ls.joyful',
    'ls.joyous',
    'wagtail.contrib.modeladmin',

    'holons',
    'django_mailbox',
    'accounts',
    'invitation',
    'social',
    'email_api',
    'rays',
    'fora',
    'moneta',
    'relations',
    'health',
    'campaigns',
    'timer',
    'meetings',
    'purpose',
    'subscription',
    'schedule',
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'holons.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'holons.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'holons',
        'USER': 'holons',
        'PASSWORD': 'holons',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/usg/'

STATIC_ROOT = os.path.join(str(BASE_DIR), "static/")
MEDIA_ROOT = os.path.join(str(BASE_DIR), "usg/")

STATICFILES_DIRS = [
    os.path.join(str(BASE_DIR), "../static/build"),
]

MODOBOA_MAIL_API_URL = ""
MODOBOA_MAIL_API_KEY = ""
SENDGRID_API_KEY = ""
SENDGRID_DOMAINS_API_KEY = ""
SENDGRID_DOMAINS_SUBUSER = ""
SENDGRID_DOMAINS_IP = ""

MASTER_RAY_PK = 

TELEGRAM_API_ID = 
TELEGRAM_API_HASH = ''
MATRIX_MASTER_USER = ''
MATRIX_MASTER_PASSWORD = ''

# Reddit settings / 
REDDIT_URL = ''
REDDIT_OAUTH_URL = ''
REDDIT_CLIENT_ID = ''
REDDIT_CLIENT_SECRET = ''
REDDIT_PASSWORD = ''
REDDIT_USERNAME = ''

TWILIO_SID = ''
TWILIO_TOKEN = ''

CEO_PHONE = ''
CTO_PHONE = ''

SESSION_COOKIE_AGE = 180*24*60*60  # 180 days

TAIGA_API_URL = ''
TAIGA_HEADERS = {'Content-type': 'application/json', 'Authorization': 'Token ' + ''}
TELEPORT_API_URL = ''
LOGIN_API_HOSTNAME = ''

WAGTAIL_SITE_NAME = 'Holons'
JOYOUS_THEME_CSS = "/static/joyous/css/joyous_forest_theme.css"
USERPIC_UPLOAD_DIR = 'usg/soulspics'

X_FRAME_OPTIONS = 'ALLOWALL'
XS_SHARING_ALLOWED_METHODS = ['POST','GET','OPTIONS', 'PUT', 'DELETE']
DEFAULT_USERPIC = 'static/img/soul-pic3.jpg'

RAY_SOURCES = [
    'mercury',
    'odysseus',
    'athena',
    'talant',
    'moneta',
    'fora',
    'pheme',
    'grintender',
]

DEFAULT_RAY_MESSAGES = {
    'mercury': 'Hello from Mercury',
    'odysseus': 'Hello from Odysseus',
    'athena': 'Hello from Athena',
    'talant': 'Hello from Talant',
    'moneta': 'Hello from Moneta',
    'fora': 'Hello from Fora',
    'pheme': 'Hello from Pheme',
    'grintender': 'Hello from Grintender',
}

IMPERSONATE_MENU_AVAILABLE_TO = [
  'disabled_01',
  'disabled_02',
  'disabled_03',
  'disabled_04',
  'disabled_05',
  'disabled_08',
  '79219890902',
  '79213173065',
  '79136661890',
]

IMPERSONATE_PROFILES = [
    'disabled_01',
    'disabled_02',
    'disabled_03',
    'disabled_04',
    'disabled_05',
    'disabled_08',
    '79219890902',
    '79213173065',
    '79136661890',
]

RAYS_SOURCE = 'Talent HbAI'

HASHID_FIELD_SALT = "2V2wMPUk7VLAfQrAdanqNsB4kmUQxgRL"

ACCOUNT_STATUSES = [
  'core',
  'classic',
  'gold',
  'coin',
]

STRIPE_API_VERSION = '2020-08-27'
STRIPE_SECRET_KEY = 'sk_test_51Id0AKL8b8L0s6Ju46st0mpc8rvymE6S5efXUQLcH2MnEaFGCTxPAzjtQOkv1lZKFYDorGIVnR1gkJnDLNShjppj00BEGaeCf9'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51Id0AKL8b8L0s6Ju6j7Mzj1gkNcH1yObWYDH5UcjSLH0fGzqyZ26Moq6sHUV13txiuMi4LqFMLWpmAtnDhlW8sWF00ERn97Eso'
STRIPE_WH_SIGNING_SECRET = 'whsec_tjmHL9XxjSVE0o6pfRj7DRsHlXv3zBqk'
SUBSCRIPTION_PRICE = 1400
SUBSCRIPTION_LENGTH_DAYS = 30
SUBSCRIPTION_PRODUCT_ID = 'prod_JZxE31o1cXWFmR'
SUBSCRIPTION_PRICE_ID = 'price_1IwnK7L8b8L0s6JuEQx1RUBI'
SUBSCRIPTION_INSTALL_FEE_PRODUCT_ID = 'prod_JaJahfUske3Ytk'
SUBSCRIPTION_INSTALL_FEE_PRICE_ID = 'price_1Ix8xKL8b8L0s6JuBxj1YC8f'
SUBSCRIPTION_DEFAULT_TYPE = 'holons core'
SUBSCRIPTION_TYPE_PLATO = 'platos full'
SUBSCRIPTION_TYPE_EARLY_ADOPT = 'early adopter'
# STRIPE webhooks
# :NB: FOR THE PROD VERSION ADD SALT TO THE URLS 
WH_PAYMENT_INTENT_SUCCEEDED = 'payment-intent-succeeded/'
WH_PAYMENT_INTENT_CANCELED = 'payment-intent-canceled/'
WH_COMMON = 'wh-common/'

LOGIN_REDIRECT_URL  = '/auth'
LOGIN_URL  = '/auth'
DEFAULT_TIMEZONE = 'Europe/Berlin'

COUNTRY_PHONE_CODES = country_codes_json
