# Generated by Django 2.2 on 2021-02-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='valid_until',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
