# Generated by Django 2.2 on 2021-02-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_token_number_of_uses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='number_of_uses',
            new_name='number_of_uses_left',
        ),
    ]
