# Generated by Django 2.2 on 2021-03-31 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('value', models.CharField(default='', max_length=255)),
                ('item_type', models.CharField(default='todo', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ManyToManyField(blank=True, related_name='purpose', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
