# Generated by Django 2.2 on 2021-07-27 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneta', '0001_initial'),
        ('purpose', '0002_auto_20210515_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, default=0)),
                ('target_value', models.FloatField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='KeyResultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='context',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='context',
            name='entities',
        ),
        migrations.RemoveField(
            model_name='context',
            name='is_handle',
        ),
        migrations.RemoveField(
            model_name='context',
            name='is_personal',
        ),
        migrations.RemoveField(
            model_name='context',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='context',
            name='title',
        ),
        migrations.AddField(
            model_name='context',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purpose_context', to='moneta.BusinessEntity'),
        ),
        migrations.AddField(
            model_name='context',
            name='user_handle_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handle_purpose_context', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='context',
            name='user_personal_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_purpose_context', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.AddField(
            model_name='purpose',
            name='context',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purpose', to='purpose.Context'),
        ),
        migrations.AddField(
            model_name='purpose',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='objective',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='purpose.Purpose'),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purpose.Objective'),
        ),
        migrations.AddField(
            model_name='keyresult',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purpose.KeyResultType'),
        ),
    ]
