# Generated by Django 2.2 on 2021-07-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0004_auto_20210727_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='purpose.Objective'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purpose', to='purpose.Context'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
