# Generated by Django 2.2 on 2021-08-13 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purpose.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purpose', '0006_auto_20210804_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresult',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_krs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purpose',
            name='plan_end_date',
            field=models.DateTimeField(default=purpose.models.now_plus_half_year),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
