# Generated by Django 2.2 on 2021-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0007_auto_20210813_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresult',
            name='interval',
            field=models.IntegerField(default=1),
        ),
    ]
