# Generated by Django 2.2 on 2021-08-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0009_auto_20210814_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='current_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='fact',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='checkin',
            name='key_result',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='purpose.KeyResult'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='plan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='interval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
