# Generated by Django 3.0.8 on 2020-10-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('is_send', models.BooleanField(default=False)),
                ('check_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
