# Generated by Django 3.0.8 on 2020-10-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rays',
            new_name='Log',
        ),
    ]
