# Generated by Django 3.0.8 on 2020-10-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20201017_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='is_send',
            new_name='is_sent',
        ),
    ]
