# Generated by Django 3.0.8 on 2020-10-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20201017_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_master', models.IntegerField(default=0)),
                ('messages_rays', models.IntegerField(default=0)),
                ('check_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
