# Generated by Django 3.0.8 on 2020-10-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_talentstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentstat',
            name='check_date',
            field=models.DateTimeField(),
        ),
    ]
