# Generated by Django 2.2 on 2021-02-05 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(default='', max_length=255)),
                ('to_name', models.CharField(default='', max_length=255)),
                ('terms_from', models.TextField(default='')),
                ('terms_to', models.TextField(default='')),
                ('consideration', models.TextField(default='')),
                ('timeframe', models.TextField(default='')),
                ('invite_token', models.CharField(default='', max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ManyToManyField(blank=True, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
