# Generated by Django 2.2 on 2021-05-04 13:59

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_offer_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='paragraphs',
            field=django_jsonfield_backport.models.JSONField(default=None, null=True),
        ),
    ]
