# Generated by Django 2.2 on 2021-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0007_offer_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
