# Generated by Django 2.2 on 2021-05-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0010_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='consideration',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='relations.Offer'),
        ),
    ]
