# Generated by Django 2.2 on 2021-05-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0011_auto_20210520_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='contract',
            new_name='offer',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='relations.Offer'),
        ),
    ]
