# Generated by Django 2.2 on 2021-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0012_auto_20210520_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='relations.Offer'),
        ),
    ]
