# Generated by Django 2.2 on 2021-05-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0013_auto_20210522_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='relations.Offer'),
        ),
    ]
