# Generated by Django 2.2 on 2021-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0024_remove_invoice_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_membership_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
