# Generated by Django 2.2 on 2021-06-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0025_offer_is_membership_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='relations.Offer'),
        ),
    ]
