# Generated by Django 2.2 on 2021-07-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0036_auto_20210724_1524'),
        ('relations', '0034_auto_20210729_2053'),
    ]

    operations = [
    ]
