# Generated by Django 2.2 on 2021-05-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210527_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
