# Generated by Django 2.2 on 2021-05-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20210527_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
