# Generated by Django 2.2 on 2021-05-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20210527_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
