# Generated by Django 2.2 on 2021-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20210731_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_intent',
            field=models.CharField(default='', max_length=255),
        ),
    ]
