# Generated by Django 2.2 on 2021-08-06 15:29

from django.conf import settings
from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0011_auto_20210804_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('payment_method_id', models.CharField(default='', max_length=255, verbose_name="Card's payment_method id inside Stripe")),
                ('card_fingerprint', models.CharField(default='fail', max_length=255, verbose_name="Stripe's hash for the Card")),
                ('last4', models.CharField(default=None, max_length=4, null=True, verbose_name='Last 4 digits of the card')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Can this card be used for payments?')),
                ('owner', models.ManyToManyField(blank=True, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ManyToManyField(blank=True, related_name='cards', to='subscription.Payment', verbose_name='Payment, made using the card')),
            ],
        ),
    ]
