# Generated by Django 2.2 on 2021-08-06 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20210806_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='brand',
            field=models.CharField(default='', max_length=255, verbose_name="Card's brand, eg Visa, MasterCard etc"),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Person who can use the card (might be multiple)'),
        ),
    ]
