# Generated by Django 2.2 on 2021-08-08 08:02

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_auto_20210806_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_fingerprint',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='last4',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=14, null=True, verbose_name='How much do we pay'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_intent',
            field=models.CharField(default='', max_length=255, verbose_name='Payment intent id inside Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='fail', max_length=255, verbose_name='Was the payment successful?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.Subscription', verbose_name='Subscription for which we are paying'),
        ),
    ]
