# Generated by Django 2.2 on 2021-08-05 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneta', '0002_paysendaccount_stripeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysendaccount',
            name='card_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('value', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
