# Generated by Django 2.2 on 2021-02-09 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, to='social.Graph')),
                ('user', models.ManyToManyField(blank=True, related_name='social', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
