# Generated by Django 2.2 on 2021-02-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
