# Generated by Django 3.0.8 on 2020-10-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='beneficiary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
