# Generated by Django 2.2 on 2020-12-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0040_auto_20201028_1649'),
        ('campaigns', '0002_campaign_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='rays.RayTemplate')),
            ],
        ),
    ]
