# Generated by Django 2.2 on 2021-07-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='template',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rays.RayTemplate'),
        ),
    ]
