# Generated by Django 3.0.8 on 2020-07-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worked_hours', models.DateTimeField()),
                ('paid_hours', models.DateTimeField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='work_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('timer_start', models.DateTimeField()),
                ('timer_stop', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
