# Generated by Django 2.2 on 2021-02-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneta', '0001_initial'),
        ('timer', '0002_auto_20201216_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_period',
            name='business_entity',
            field=models.ManyToManyField(blank=True, to='moneta.BusinessEntity'),
        ),
    ]
