# Generated by Django 2.2 on 2021-02-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_auto_20210204_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_period',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
