# Generated by Django 2.2 on 2021-04-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0006_auto_20210414_0345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_info',
            new_name='UserInfo',
        ),
    ]
