# Generated by Django 2.2 on 2021-07-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0036_auto_20210724_1524'),
        ('timer', '0007_auto_20210414_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='workperiod',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relations.Offer'),
        ),
    ]
