# Generated by Django 2.2 on 2021-08-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0009_auto_20210726_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workperiod',
            name='commitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relations.Offer'),
        ),
    ]
