# Generated by Django 3.0.8 on 2020-10-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForaChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('is_tech', models.BooleanField(default=False)),
                ('is_development', models.BooleanField(default=False)),
                ('is_news', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('is_coding', models.BooleanField(default=False)),
                ('is_humor', models.BooleanField(default=False)),
                ('is_crypto', models.BooleanField(default=False)),
                ('is_design', models.BooleanField(default=False)),
                ('is_marketing', models.BooleanField(default=False)),
                ('is_data', models.BooleanField(default=False)),
                ('is_science', models.BooleanField(default=False)),
                ('is_jobs', models.BooleanField(default=False)),
            ],
        ),
    ]
