# Generated by Django 3.0.8 on 2020-10-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forachannel',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
