# Generated by Django 3.0.8 on 2020-07-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailboxes',
            field=models.ManyToManyField(blank=True, related_name='users', to='email_api.Mailbox'),
        ),
    ]
