# Generated by Django 3.0.8 on 2020-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0002_raysource'),
        ('accounts', '0002_user_mailboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rays',
            field=models.ManyToManyField(blank=True, related_name='users', to='rays.RaySource'),
        ),
    ]
