# Generated by Django 3.0.8 on 2020-08-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0006_auto_20200819_1344'),
        ('accounts', '0003_user_rays'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ray_messages',
            field=models.ManyToManyField(blank=True, related_name='users', to='rays.UpworkTalent'),
        ),
    ]
