# Generated by Django 2.2 on 2021-01-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_mailbox_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mailbox_settings',
        ),
    ]
