# Generated by Django 2.2 on 2021-02-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0042_directmessage_messagethread'),
        ('accounts', '0006_remove_user_mailbox_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='rays_direct_treads',
            field=models.ManyToManyField(blank=True, related_name='users', to='rays.MessageThread'),
        ),
    ]
