# Generated by Django 2.2 on 2021-03-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210310_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(max_length=255, unique=False, null=True, blank=True),
        ),
    ]
