# Generated by Django 2.2 on 2021-04-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210331_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userpic_file',
        ),
        migrations.AddField(
            model_name='user',
            name='userpic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
