# Generated by Django 2.2 on 2021-04-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_ray_direct_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ray_direct_messages',
            new_name='ray_direct_messages_from',
        ),
    ]
