# Generated by Django 2.2 on 2021-04-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0048_auto_20210218_1728'),
        ('accounts', '0017_auto_20210415_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ray_direct_messages_to',
            field=models.ManyToManyField(blank=True, related_name='user_to', to='rays.DirectMessage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ray_direct_messages_from',
            field=models.ManyToManyField(blank=True, related_name='user_from', to='rays.DirectMessage'),
        ),
    ]
