# Generated by Django 2.2 on 2021-04-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210415_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ray_direct_messages_from',
            new_name='rays_dm_recieved',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ray_direct_messages_to',
            new_name='rays_dm_sent',
        ),
    ]
