# Generated by Django 2.2 on 2021-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210415_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rays_dm_recieved',
            field=models.ManyToManyField(blank=True, related_name='user_to', to='rays.DirectMessage'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rays_dm_sent',
            field=models.ManyToManyField(blank=True, related_name='user_from', to='rays.DirectMessage'),
        ),
    ]
