# Generated by Django 2.2 on 2021-05-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_is_profile_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='account_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='userpic',
            field=models.ImageField(default='static/img/soul-pic3.jpg', null=True, upload_to='usg/soulspics'),
        ),
    ]
