# Generated by Django 2.2 on 2021-05-12 13:01

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210510_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
