# Generated by Django 3.0.8 on 2020-07-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpworkTalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('guid', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
