# Generated by Django 3.0.8 on 2020-08-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0002_raysource'),
    ]

    operations = [
        migrations.AddField(
            model_name='upworktalent',
            name='ray_source',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='rays.RaySource'),
        ),
    ]
