# Generated by Django 3.0.8 on 2020-08-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0003_upworktalent_ray_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='raysource',
            name='stop_words',
            field=models.TextField(default=''),
        ),
    ]
