# Generated by Django 3.0.8 on 2020-08-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0004_raysource_stop_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raysource',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
