# Generated by Django 3.0.8 on 2020-08-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0005_auto_20200819_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upworktalent',
            name='guid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
