# Generated by Django 3.0.8 on 2020-08-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0006_auto_20200819_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upworktalent',
            name='ray_source',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rays.RaySource'),
        ),
    ]
