# Generated by Django 3.0.8 on 2020-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0008_auto_20200820_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, default=None)),
                ('owner', models.IntegerField(blank=True, default=None)),
                ('assignee', models.IntegerField(blank=True, default=None)),
            ],
        ),
    ]
