# Generated by Django 3.0.8 on 2020-08-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0009_messageassigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageassigned',
            name='message_id',
        ),
        migrations.AddField(
            model_name='messageassigned',
            name='message',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='rays.UpworkTalent'),
        ),
    ]
