# Generated by Django 3.0.8 on 2020-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0011_auto_20200825_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.CharField(default=None, max_length=1024)),
                ('name', models.CharField(default=None, max_length=1024)),
                ('first_name', models.CharField(default=None, max_length=1024)),
                ('last_name', models.CharField(default=None, max_length=1024)),
                ('company_name', models.CharField(default=None, max_length=1024)),
                ('title', models.CharField(default=None, max_length=1024)),
                ('company_id', models.CharField(default=None, max_length=1024)),
                ('company_url', models.CharField(default=None, max_length=1024)),
                ('summary', models.TextField(default=None)),
                ('location', models.CharField(default=None, max_length=256)),
                ('duration', models.CharField(default=None, max_length=256)),
                ('past_role', models.CharField(default=None, max_length=256)),
                ('past_company', models.CharField(default=None, max_length=256)),
                ('past_company_url', models.CharField(default=None, max_length=256)),
                ('profile_image_url', models.CharField(default=None, max_length=1024)),
                ('shared_connections_count', models.CharField(default=None, max_length=1024)),
                ('vmid', models.CharField(default=None, max_length=1024)),
                ('is_premium', models.BooleanField(default=False)),
                ('query', models.CharField(default=None, max_length=1024)),
                ('timestamp', models.CharField(default=None, max_length=1024)),
                ('source', models.CharField(default=None, max_length=256)),
                ('total_jobs', models.IntegerField(default=None)),
                ('completed_jobs', models.IntegerField(default=None)),
                ('total_earnings', models.IntegerField(default=None)),
                ('total_hours', models.IntegerField(default=None)),
                ('hourly_rate', models.IntegerField(default=None)),
            ],
        ),
    ]
