# Generated by Django 3.0.8 on 2020-09-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0013_auto_20200904_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='completed_jobs',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='hourly_rate',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='summary',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='total_earnings',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='total_hours',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='total_jobs',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
