# Generated by Django 3.0.8 on 2020-09-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0014_auto_20200904_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='company_id',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='company_name',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='company_url',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='first_name',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='last_name',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='profile_image_url',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='profile_url',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='query',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='shared_connections_count',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='timestamp',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='title',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='vmid',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
