# Generated by Django 3.0.8 on 2020-09-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0019_raysource_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstats',
            name='pub_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
