# Generated by Django 3.0.8 on 2020-09-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0020_clientstats_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstats',
            name='hire_rate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientstats',
            name='rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
