# Generated by Django 3.0.8 on 2020-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0021_auto_20200909_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='raysource',
            name='category_filter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='raysource',
            name='skills_filter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='raysource',
            name='title_filter',
            field=models.TextField(default=''),
        ),
    ]
