# Generated by Django 3.0.8 on 2020-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0024_auto_20200915_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raysource',
            name='budget_fixed',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='raysource',
            name='budget_rate',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
