# Generated by Django 3.0.8 on 2020-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0025_auto_20200915_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raysource',
            name='is_budget_empty_ok',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
