# Generated by Django 3.0.8 on 2020-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0026_auto_20200915_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raysource',
            name='budget_fixed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='raysource',
            name='budget_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
