# Generated by Django 3.0.8 on 2020-09-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0028_raysource_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raysource',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
