# Generated by Django 3.0.8 on 2020-09-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0029_auto_20200927_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raysource',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='upworktalent',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
