# Generated by Django 3.0.8 on 2020-10-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0033_raysource_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='upworktalent',
            name='provider',
            field=models.TextField(default='upwork'),
        ),
    ]
