# Generated by Django 3.0.8 on 2020-10-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0036_auto_20201015_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='RayTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bids_total', models.IntegerField(blank=True, default=0, null=True)),
                ('replies', models.IntegerField(blank=True, default=0, null=True)),
                ('conversions', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
