# Generated by Django 3.0.8 on 2020-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0037_raytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='upworktalent',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upworktalent',
            name='templates',
            field=models.ManyToManyField(blank=True, default=False, related_name='tpl_messages', to='rays.RaySource'),
        ),
    ]
