# Generated by Django 2.2 on 2021-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0040_auto_20201028_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='raytemplate',
            name='is_archived',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
