# Generated by Django 2.2 on 2021-02-17 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0041_raytemplate_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1024)),
                ('body', models.TextField()),
                ('type', models.CharField(max_length=128)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('provider', models.TextField(default='holons')),
                ('message_thread', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rays.MessageThread')),
            ],
        ),
    ]
