# Generated by Django 2.2 on 2021-02-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0042_directmessage_messagethread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('message_thread', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='ray', to='rays.MessageThread')),
            ],
        ),
    ]
