# Generated by Django 2.2 on 2021-02-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0044_auto_20210217_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ray',
            name='message_thread',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ray', to='rays.MessageThread'),
        ),
    ]
