# Generated by Django 2.2 on 2021-02-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0046_auto_20210217_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ray',
            name='message_thread',
        ),
        migrations.AddField(
            model_name='ray',
            name='message_thread',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='ray', to='rays.MessageThread'),
        ),
    ]
