# Generated by Django 2.2 on 2021-02-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0047_auto_20210217_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='ray',
            name='created_by',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ray',
            name='message_thread',
            field=models.ManyToManyField(blank=True, default=None, related_name='ray', to='rays.MessageThread'),
        ),
    ]
