# Generated by Django 2.2 on 2021-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0048_auto_20210218_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='RayCanned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
