# Generated by Django 2.2 on 2021-06-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0050_auto_20210423_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='raysource',
            name='key_words',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='upworktalent',
            name='country',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
