# Generated by Django 2.2 on 2021-07-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0053_auto_20210628_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raysource',
            name='key_words',
            field=models.TextField(default='', null=True),
        ),
    ]
