# Generated by Django 2.2 on 2021-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0054_auto_20210704_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='upworktalent',
            name='trace_message',
            field=models.TextField(blank=True),
        ),
    ]
