# Generated by Django 2.2 on 2021-07-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0055_upworktalent_trace_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='upworktalent',
            name='category',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='upworktalent',
            name='skills',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
