# Generated by Django 2.2 on 2021-07-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0056_auto_20210709_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upworktalent',
            name='category',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='upworktalent',
            name='skills',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
