# Generated by Django 2.2 on 2021-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0057_auto_20210710_1641'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='upworktalent',
            index=models.Index(fields=['guid'], name='rays_upwork_guid_f8f397_idx'),
        ),
    ]
