# Generated by Django 2.2 on 2021-07-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rays', '0058_auto_20210715_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upworktalent',
            name='category',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='upworktalent',
            name='skills',
            field=models.CharField(default='', max_length=8192),
        ),
    ]
