# Generated by Django 3.0.8 on 2020-07-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='dns_dkim1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='dns_dkim2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='dns_mail_cname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='domain',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='domain_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='domain_ip',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='incoming_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='sendgrid_subuser',
            field=models.CharField(default='', max_length=255),
        ),
    ]
