# Generated by Django 3.0.8 on 2020-07-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0002_auto_20200729_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='dns_dkim1_data',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='dns_dkim2_data',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='dns_mail_cname_data',
            field=models.CharField(default='', max_length=255),
        ),
    ]
