# Generated by Django 3.0.8 on 2020-08-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0003_auto_20200729_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_snoozed', models.BooleanField(default=False)),
                ('snoozed_until', models.DateTimeField(default=None)),
            ],
        ),
    ]
