# Generated by Django 3.0.8 on 2020-08-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0007_auto_20200826_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontapp_token', models.TextField(blank=True, default='')),
            ],
        ),
    ]
