# Generated by Django 3.0.8 on 2020-08-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0009_mailbox_is_frontapp_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='frontapp_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
