# Generated by Django 3.0.8 on 2020-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0011_emailimportstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailimportstatus',
            name='completed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailimportstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailimportstatus',
            name='started_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
