# Generated by Django 3.0.8 on 2020-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0008_auto_20190219_1553'),
        ('email_api', '0014_auto_20200830_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailConversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255)),
                ('subject', models.CharField(default='', max_length=1024)),
                ('status', models.CharField(max_length=255)),
                ('messages', models.ManyToManyField(blank=True, to='django_mailbox.Message')),
            ],
        ),
    ]
