# Generated by Django 3.0.8 on 2020-08-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0008_auto_20190219_1553'),
        ('email_api', '0015_mailconversations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailConversations',
            new_name='EmailConversations',
        ),
    ]
