# Generated by Django 3.0.8 on 2020-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0016_auto_20200830_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
