# Generated by Django 2.2 on 2021-01-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0017_mailbox_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
