# Generated by Django 2.2 on 2021-01-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_mailbox_settings'),
        ('email_api', '0018_mailbox_is_paused'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
    ]
