# Generated by Django 2.2 on 2021-01-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0008_auto_20190219_1553'),
        ('email_api', '0021_sharedmailmessages_assigned_to_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedMailMessages',
            new_name='SharedMailMessage',
        ),
    ]
