# Generated by Django 2.2 on 2021-01-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_api', '0022_auto_20210109_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconversations',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='conversation', to='django_mailbox.Message'),
        ),
    ]
